version: "0.2"
language: "en"
words:
  - andreas
  - commitlint
  - coreutils
  - inplace
  - nohup
  - pacman
  - pango
  - polybar
  - remigius
  - rubygems
  - shellcheck
  - statusline
  - subshell
  - swiftbar
  - xbar
